name: kostku
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.9.0
  image_picker: ^1.0.4
  camera: ^0.10.5
  geolocator: ^10.1.0
  intl: ^0.18.1
 #flutter_local_notifications: ^13.0.0
  fl_chart: ^0.65.0
  pdf: ^3.10.7
  printing: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
